name = "Path Generator"
author = "R3vo"
prefix = "PG"
mainprefix = "x"

[files]
include = [
    "keys/**"
]

[version]
major = 1
minor = 0
patch = 0
git_hash = 0

[hemtt.release]
archive = true

[lints.sqf.command_case]
severity = "Error"
options.ignore = [
    "AGLtoASL",
    "ASLtoAGL",
    "groupID"
]

[lints.sqf.banned_commands]
options.banned = [
    "execVM",
    "opfor",
    "blufor",
    "resistance",
    "and",
    "or",
    "not",
    "vehicle"
]

[lints.sqf.var_all_caps]
enabled = true

##########################################################################################
############################## LAUNCH DEFAULT ############################################
##########################################################################################
[hemtt.launch.default]

workshop = [
    "450814997",    # CBA_A3
    "1751569185",   # Pythia
    "1387934106",   # 7erra's Editing Extensions
    "2073243184",   # 3Den Stringtable Viewer
    "623475643"     # 3den Enhanced
]

parameters = [
    "-setThreadCharacteristics",
    "-limitFPS=60"
]

mission = "PathGenerator.VR" # Mission to launch directly into the editor with
executable = "arma3_x64"